const router = require('express').Router();
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const warehouseRoutes = require('./warehouse.routes');
const locationRoutes = require('./location.routes');
const supplierRoutes = require('./supplier.routes');
const customerRoutes = require('./customer.routes');
const categoryRoutes = require('./category.routes');
const brandRoutes = require('./brand.routes');
const productRoutes = require('./product.routes');
const branchRoutes = require('./branch.routes');
const purchaseOrderRoutes = require('./purchaseOrder.routes');
const goodsReceiptRoutes = require('./goodsReceipt.routes');
const stockInRoutes = require('./stockIn.routes');
const stockOutRoutes = require('./stockOut.routes');
const stockTransferRoutes = require('./stockTransfer.routes');
const stockAdjustmentRoutes = require('./stockAdjustment.routes');
const stockOpnameRoutes = require('./stockOpname.routes');
const stockMovementRoutes = require('./stockMovement.routes');
const reportRoutes = require('./report.routes');
const auditRoutes = require('./audit.routes');
const settingRoutes = require('./setting.routes');

router.get('/health', (req, res) => res.json({ success: true, message: 'OK', data: { uptime: process.uptime() } }));
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/branches', branchRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/locations', locationRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/customers', customerRoutes);
router.use('/categories', categoryRoutes);
router.use('/brands', brandRoutes);
router.use('/products', productRoutes);
router.use('/purchase-orders', purchaseOrderRoutes);
router.use('/goods-receipts', goodsReceiptRoutes);
router.use('/stock-in', stockInRoutes);
router.use('/stock-out', stockOutRoutes);
router.use('/transfers', stockTransferRoutes);
router.use('/adjustments', stockAdjustmentRoutes);
router.use('/opnames', stockOpnameRoutes);
router.use('/movements', stockMovementRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/settings', settingRoutes);

module.exports = router;
