const { ROLES } = require('../models/user.model');

const ALL = [
  'dashboard:view',
  'products:view', 'products:create', 'products:update', 'products:delete',
  'products:import', 'products:export',
  'categories:view', 'categories:manage',
  'brands:view', 'brands:manage',
  'suppliers:view', 'suppliers:manage',
  'customers:view', 'customers:manage',
  'warehouses:view', 'warehouses:manage',
  'locations:view', 'locations:manage',
  'purchase_orders:view', 'purchase_orders:manage', 'purchase_orders:approve',
  'goods_receipts:view', 'goods_receipts:manage',
  'stock_ins:view', 'stock_ins:manage',
  'stock_outs:view', 'stock_outs:create', 'stock_outs:approve',
  'transfers:view', 'transfers:create', 'transfers:approve',
  'adjustments:view', 'adjustments:create', 'adjustments:approve',
  'opnames:view', 'opnames:create', 'opnames:approve',
  'movements:view', 'movements:export',
  'reports:view', 'reports:export',
  'notifications:view',
  'users:view', 'users:manage',
  'audit:view',
  'settings:view', 'settings:manage',
  'backup:manage',
];

const VIEW_ALL = ALL.filter((p) => p.endsWith(':view') || p.includes(':export'));

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: ['*'],
  [ROLES.MANAGER_GUDANG]: [
    'dashboard:view',
    'products:view', 'products:create', 'products:update', 'products:import', 'products:export',
    'categories:view', 'categories:manage',
    'brands:view', 'brands:manage',
    'suppliers:view',
    'customers:view',
    'warehouses:view', 'warehouses:manage',
    'locations:view', 'locations:manage',
    'purchase_orders:view', 'purchase_orders:manage',
    'goods_receipts:view', 'goods_receipts:manage',
    'stock_ins:view', 'stock_ins:manage',
    'stock_outs:view', 'stock_outs:create', 'stock_outs:approve',
    'transfers:view', 'transfers:create', 'transfers:approve',
    'adjustments:view', 'adjustments:create', 'adjustments:approve',
    'opnames:view', 'opnames:create', 'opnames:approve',
    'movements:view', 'movements:export',
    'reports:view', 'reports:export',
    'notifications:view',
    'audit:view',
  ],
  [ROLES.STAFF_GUDANG]: [
    'dashboard:view',
    'products:view', 'products:create', 'products:update',
    'categories:view',
    'brands:view',
    'suppliers:view',
    'customers:view',
    'warehouses:view',
    'locations:view',
    'purchase_orders:view',
    'goods_receipts:view', 'goods_receipts:manage',
    'stock_ins:view', 'stock_ins:manage',
    'stock_outs:view', 'stock_outs:create',
    'transfers:view', 'transfers:create',
    'adjustments:view', 'adjustments:create',
    'opnames:view', 'opnames:create',
    'movements:view',
    'notifications:view',
  ],
  [ROLES.PURCHASING]: [
    'dashboard:view',
    'products:view', 'products:import', 'products:export',
    'categories:view',
    'brands:view',
    'suppliers:view', 'suppliers:manage',
    'customers:view',
    'warehouses:view',
    'locations:view',
    'purchase_orders:view', 'purchase_orders:manage',
    'goods_receipts:view', 'goods_receipts:manage',
    'stock_ins:view', 'stock_ins:manage',
    'stock_outs:view',
    'transfers:view',
    'adjustments:view',
    'opnames:view',
    'movements:view', 'movements:export',
    'reports:view', 'reports:export',
    'notifications:view',
  ],
  [ROLES.FINANCE]: [
    'dashboard:view',
    'products:view',
    'suppliers:view',
    'warehouses:view',
    'purchase_orders:view', 'purchase_orders:approve',
    'goods_receipts:view',
    'stock_ins:view',
    'stock_outs:view',
    'transfers:view',
    'adjustments:view',
    'opnames:view',
    'movements:view', 'movements:export',
    'reports:view', 'reports:export',
    'notifications:view',
  ],
  [ROLES.VIEWER]: VIEW_ALL.filter(
    (p) => !p.includes('users') && !p.includes('audit') && !p.includes('settings') && !p.includes('backup')
  ),
};

const getPermissions = (role) => ROLE_PERMISSIONS[role] || [];

module.exports = { ALL, ROLE_PERMISSIONS, getPermissions };
